Update docstings and arg names of InterpolatedVolumeParameter and InterpolatedFlowParameter
pywr/pywr pull request #890
Opened 2020-05-21 21:49 UTC by Batch21

2020-05-21 23:13 UTC, jetuk commented
@Batch21 what have you done here?

2020-05-22 07:14 UTC, Batch21 commented
oops, I created the branch from the wrong location. Should be fixed after a bit of Git fun.

2020-05-22 09:06 UTC, jetuk commented
Shall we close this then?

2020-05-22 09:50 UTC, Batch21 commented
Is it not OK as its now branched correctly from master?

2020-05-22 10:03 UTC, jetuk commented
Oh I missed the force push, sorry.

2020-05-22 10:06 UTC, jetuk requested changes
Can we rename the variable in `InterpolatedFlowParameter.load` it currently sets the flows key in a volumes variable which is just confusing.

2020-05-22 10:06 UTC, jetuk commented on pywr/parameters/parameters.py
> +    volumes: array_like
flows.

2020-05-22 13:05 UTC, jetuk approved these changes

2020-05-22 13:05 UTC, merged