Implement a 2-stage loading scheme for nodes.
pywr/pywr pull request #945
Opened 2020-11-18 21:45 UTC by jetuk

The changes here remove the existing `load` classmethod for
nodes. These are replaced with a new classmethod `pre_load`
which performs the object instantiation. After this itial
stage the parameters and recorders are fully loaded. Finally,
any parameter references are assigned to node attributes.

This resolves the circular loading between nodes and parameters.
However, it has required somworking of node init methods
which has impacted on the JSON schema for the nodes. Overall
this should make the JSON schema and init method arguments
more consistent.

Fixes #380.

2020-11-20 14:56 UTC, jetuk commented on pywr/_model.pyx
> -    def _get_node_from_ref(cls, model, node_name):
Reinstate this and defer to `model.nodes`, but with a deprecation warning.

2020-11-21 16:32 UTC, jetuk commented on pywr/_model.pyx
> -    def _get_node_from_ref(cls, model, node_name):
Done in latest commit.

2020-11-30 22:26 UTC, Batch21 requested changes
I've tested this on a few relatively complex models and generally it is working well

2020-11-30 22:26 UTC, Batch21 commented on pywr/nodes.py
>  class RollingVirtualStorage(Drawable, _core.RollingVirtualStorage, metaclass=NodeMeta):
This need to have the `Loadable`  Mixin added, as well as these attributes:

```python
 __parameter_attributes__ = ('min_volume', 'max_volume')
__node_attributes__ = ('nodes', )
```

2020-11-30 22:26 UTC, Batch21 commented on pywr/nodes.py
>  class AggregatedStorage(Drawable, _core.AggregatedStorage, metaclass=NodeMeta):
Needs to inherit `Loadable` and have attributes added.

2020-12-02 12:52 UTC, jetuk commented
@Batch21 I believe I have addressed your comments here.

2020-12-06 10:36 UTC, Batch21 approved these changes
changes look good, thanks

2020-12-09 20:12 UTC, merged

2020-12-09 20:12 UTC, jetuk commented
Thanks @Batch21